---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 15-create-docker-certd
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,Cg==
          mode: 420
          overwrite: true
          path: /etc/docker/certs.d/.ignore
          user:
            name: root
